### ISSUE TITLE
`KeyError: 'codecs'`

### ISSUE THREAD

**Issue by s16h** [SEERNET/deepaffects-python#18]
## Versions:

- MediaInfo: v18.08.1
- pymediainfo: 2.3.0 

## Exception

```
Traceback (most recent call last):
  File "diarize.py", line 19, in <module>
    main()
  File "diarize.py", line 9, in main
    body = deepaffects.DiarizeAudio.from_file(file_name='deepaffects_test.flac')
  File "/Users/.../venv/lib/python3.6/site-packages/deepaffects/models/diarize_audio.py", line 294, in from_file
    codec = media_info.tracks[0].__dict__['codecs']
KeyError: 'codecs'
```

Changing `media_info.tracks[0].__dict__['codecs']` to `media_info.tracks[0].__dict__['audio_codecs']` fixes the problem. Not sure how it affects older versions.

**Comment by sushant-hiray** [comment]
Thanks for reporting the issue @s16h 

Let me check version compatibilities and deploy a new version.

**Comment by s16h** [comment]
How did this go @sushant-hiray?

**Comment by sushant-hiray** [comment]
You can find the latest code snippets on our [documentation portal](https://docs.deepaffects.com/docs/introduction.html)

Let us know if you face any issues with the code snippets posted there.
