### ISSUE TITLE
cannot get expected output from Diarization API

### ISSUE THREAD

**Issue by cici20052016** [SEERNET/deepaffects-python#33]
i was following the instruction here to analyze a local wav file for speaker diarization. 

```
import deepaffects
from deepaffects.rest import ApiException
from pprint import pprint

# Configure API key authorization: UserSecurity
deepaffects.configuration.api_key['apikey'] = '<API_KEY>'

# create an instance of the API class
api_instance = deepaffects.DiarizeApiV2()
body = deepaffects.DiarizeAudio.from_file("/path/to/file") # DiarizeAudio | Audio object that needs to be diarized.

try:
    api_response = api_instance.sync_diarize_audio(body)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling DiarizeApiV2->async_diarize_audio: %s\n" % e)
```

I did not get expected results like this:
# Sync:

{
  "num_speakers": 2,
  "segments":[
        {
            "speaker_id": "speaker1",
            "start": 0,
            "end": 1
        }
    ]
}

Instead I got sth like this:
{
  "content": 'some-encoding-here',
  'encoding': 'mp3',
 'language_code': 'en-US',
 'sample_rate': '8000'
}

I cannot find instruction in github documentation on how to get the expected results, please advice, thanks!

**Comment by sushant-hiray** [comment]
Hi @cici20052016 

Please follow the documentation here: 
https://docs.deepaffects.com/docs/speaker-diairization-api.html

We no longer support sync api in the diarization api. You need to try the async api as mentioned the docs. Let me know if you face any issues with that api.

**Comment by cici20052016** [comment]
thanks, the code works, just curious if/how to make diarization work without webhook?

**Comment by sushant-hiray** [comment]
Currently we don't support a flow apart from webhooks. However, you can use websites like [webhook.site](https://webhook.site/) to spoof a webhook url without actually generating one. 

I'm closing this issue for now, let me know if you need any further help. 
Thanks.
