### ISSUE TITLE
Error on reading/passing audio file 

### ISSUE THREAD

**Issue by sithara** [SEERNET/deepaffects-python#34]
Hi

I was trying to execute the code snippet  in https://docs.deepaffects.com/docs/speaker-diairization-api.html but for some reason I cannot get in working. Could you please help me figure out if I missed any steps ? Please find the attached error screenshot 

![capture](https://user-images.githubusercontent.com/3234964/50434609-e1d69880-0903-11e9-8d23-d654f87b3dc3.PNG)

The error occurs at line `body = deepaffects.DiarizeAudio.from_file("/path/to/file")`

**Comment by sushant-hiray** [comment]
Hi @sithara 

You need to install MediaInfo from [here](https://mediaarea.net/en/MediaInfo)

**Comment by sithara** [comment]
Hi @sushant-hiray  I have already installed MediaInfo but still see the issue

**Comment by sushant-hiray** [comment]
What is the extension of your file?

**Comment by sithara** [comment]
`.wav`

**Comment by sushant-hiray** [comment]
Just to be sure, if you've installed the mediainfo dlls and installed pymediainfo? pymediainfo is just a wrapper on the software on the link above

**Comment by sithara** [comment]
![image](https://user-images.githubusercontent.com/3234964/50467638-f7ae9100-09c9-11e9-8dc4-3ebae4e44ffc.png)

Yes, I have pymediainfo also installed

**Comment by sithara** [comment]
Sorry, I had the MedioInfo stored at the incorrect path . The code seems to be working fine now 👍

**Comment by VinMing** [comment]
hi, sithara, i meet same problem.where are you store the MedioInfo .
