### ISSUE TITLE
BAD REQUEST

### ISSUE THREAD

**Issue by absin1** [SEERNET/deepaffects-python#35]
I am following [this](https://github.com/SEERNET/deepaffects-python/blob/master/docs/EmotionApi.md#sync_recognise_emotion). But I get the following error:
```
Exception when calling EmotionApi->sync_recognise_emotion: (400)
Reason: BAD REQUEST
HTTP response headers: HTTPHeaderDict({'Via': 'kong/0.13.1', 'ContentType': 'application/json', 'X-Kong-Proxy-Latency': '15', 'Access-Control-Allow-Origin': '*', 'X-Kong-Upstream-Latency': '3751', 'Server': 'gunicorn/19.7.1', 'Connection': 'keep-alive', 'Content-Length': '98', 'Content-Type': 'text/html; charset=utf-8', 'Date': 'Fri, 15 Mar 2019 12:09:17 GMT'})
HTTP response body: {"fault": {"fault_string": "BAD REQUEST", "detail": {"error_code": "com.deepaffects.BadRequest"}}}

```
What could be the problem?

**Comment by absin1** [comment]
I am using an audio file from RAVEDESS dataset:
I do `ffmpeg -i /home/absin/Downloads/03-01-01-01-01-01-01.wav`
and get this:
```
Input #0, wav, from '/home/absin/Downloads/03-01-01-01-01-01-01.wav':
  Metadata:
    encoded_by      : Adobe Systems Inc
    encoder         : Adobe Premiere Pro CS6 (Macintosh)
    date            : 2013-11-02
    creation_time   : 19:55:37
    time_reference  : 360360
  Duration: 00:00:03.30, bitrate: 909 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 48000 Hz, 1 channels, s16, 768 kb/s

```

**Comment by sushant-hiray** [comment]
Thanks for pointing out the issue @absin1 

Do you mind following the documentation over at: https://docs.deepaffects.com/docs/emotion-recognition-api.html

We're in the process of removing stale documents from this repo. 

Let me know if you face any issues.

**Comment by absin1** [comment]
Thanks @sushant-hiray

**Comment by absin1** [comment]
I have an incoming audio 16 bit PCM, is there a `chunk_generator_from_stream` like there are `chunk_generator_from_file` and `chunk_generator_from_url`.
