### ISSUE TITLE
mp3 file does not work with DiarizeEmotion

### ISSUE THREAD

**Issue by ishwara-bhat** [SEERNET/deepaffects-python#39]
I am testing DiarizeEmotion. With .wav it was fine. With .mp3 I run into 
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Exception iterating requests!"
	debug_error_string = "None"

the log shows this-

\lib\site-packages\grpc\_channel.py", line 339, in _next
                    return response
                elif cygrpc.OperationType.receive_message not in self._state.due:
                    if self._state.code is grpc.StatusCode.OK:
                        raise StopIteration()
                    elif self._state.code is not None:
                        raise self

While running, I had noticed the following:
site-packages\pydub\utils.py:165: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)

But pip install ffmpeg was already done. For avconv, it say no compatible version.

Also, please upload a tested mp3 file with corresponding metadata too, for verifying.

Thanks in advance.

**Comment by sushant-hiray** [comment]
Hi @ishwara-bhat 

Are you using windows? You might want to follow instructions here to setup your environment: https://github.com/jiaaro/pydub/blob/master/appveyor.yml#L15
Or just download from http://www.ffmpeg.org/

**Comment by ishwara-bhat** [comment]
Thanks a lot. Yes. I used windows and Anaconda. Setting PATH of ffmpeg bin folder solved this problem.
