### ISSUE TITLE
JSON Output

### ISSUE THREAD

**Issue by ishwara-bhat** [SEERNET/deepaffects-python#40]
Please check if it is possible to provide JSON output. If it is a problem for existing customers, please provide based on parameter. It will make the output handling much easier.

**Comment by sushant-hiray** [comment]
Is this for the realtime api? The outputs for the async apis are json already. For realtime api's you can directly convert protobuf to json using existing libraries: See more details here: https://stackoverflow.com/questions/19734617/protobuf-to-json-in-python

**Comment by ishwara-bhat** [comment]
Thanks for the response. It is async. But while using the client library, is it expected to be in JSON?

   responses = deep_affects_client.DiarizeEmotion(
            chunk_generator_from_file(deep_affects_input_file_path), TIMEOUT_SECONDS, metadata=metadata) 
    for response in responses:
        print("Received message")
        print(response)
The above lines do not provide JSON format.

For the production code, could we use the above library or should we use standard REST API? The above client library seems to do Diarize adn also emotion recognition. But the REST API https://docs.deepaffects.com/docs/speaker-diarization-api.html does only diarizing and https://docs.deepaffects.com/docs/emotion-recognition-api.html does only emotion recognition. I need something like what the client library gives. But the client library output is not in JSON.

1. Please confirm the approach I should take for production (APIs vs client library). 
2. If I should use bare REST API, I need to do base64 encoding. Suppose my conversation is of 30 minutes, should I send in 30 second chunks (after doing base64 encoding)? Then for each of these I should call the REST API and provide the same webhook? Or I should provide the webhook with any sequence number managed by me? Or do you recommend taking this github project and modify it to alter client library output?
Please clarify.

**Comment by ishwara-bhat** [comment]
I did further test. JSON output is fine with webhook. Sorry about confusion.
