### ISSUE TITLE
List of supported media input formats

### ISSUE THREAD

**Issue by ishwara-bhat** [SEERNET/deepaffects-python#42]
The documentation recommends sending the input format such as .WAV, .mp3 etc. without altering. Do we have full list of supported formats?  My immediate need is .m3u8.

I have .m3u8 playlists which contain .ts (DVD format I guess?) files. Does DA support it? 

And how about .aac ? Since there are too many formats out there, please confirm the list you support. Also if there is mix of Hi Fidelity music along with speech with 96000 sampling rate, again it could impact your API. 

Please provide the full list of supported formats and any conversion guidelines.

**Comment by sushant-hiray** [comment]
@ishwara-bhat you can find the list of supported encodings here: https://docs.deepaffects.com/docs/concepts.html#audio-encoding

As a rule of thumb, we support all the audio codecs which are inherently supported by ffmpeg

If there's a lot of music along with speech, it can impact the accuracy.
