### ISSUE TITLE
Speaker Enrollment and using it for interaction analytics (POST https://proxy.api.deepaffects.com/audio/generic/api/v1/async/analytics/interaction)

### ISSUE THREAD

**Issue by ishwara-bhat** [SEERNET/deepaffects-python#43]
The documentation says that we can do speaker enrollment and then use it for speaker detection API. Could we also use the enrolled speakers for interaction metrics?

**Comment by sushant-hiray** [comment]
Yes, you can pass all the parameters from speaker diarization api to the interaction analytics
